### ISSUE TITLE
error when building 'lightfm.lightfm_fast' extension on OSX

### ISSUE THREAD

**Issue by dustinstansbury** [lyst/lightfm#29]
Looks like this is an issue with the gcc compiler on 64-bit architectures, in particular the Wshorten-64-to-32 option.

Here's the error:

gcc-4.9: error: unrecognized command line option '-Wshorten-64-to-32'
error: command 'gcc-4.9' failed with exit status 1

My machine has a relatively new version of gcc, the one available from brew:

brew upgrade gcc
Error: gcc 4.9.2_1 already installed

Any ideas?

**Comment by maciejkula** [comment]
Apparently that is a clang-only flag, it should not be given to gcc. Can you tell me what OSX version you are on and which Python distribution you are using?

**Comment by dustinstansbury** [comment]
Yosemite 10.10.3
Python 2.7.6

**Comment by maciejkula** [comment]
Can you paste the output of `which python` please?

**Comment by maciejkula** [comment]
I managed to reproduce your issue, it arises because you are building against the default OSX Python distribution. Installing Python from brew, macports, or the anaconda distribution should solve this problem while I look for a better solution.

**Comment by maciejkula** [comment]
Can you have a look if https://github.com/lyst/lightfm/pull/30 fixes the issue for you?

**Comment by dustinstansbury** [comment]
That definitely fixed the error related to -Wshorten-64-to-32 flag, thank you. 

However, I'm still getting some assembly errors. It's apparently related to this: http://stackoverflow.com/a/10894096.  

Seems like a possible fix is to replace the flag -march=native with  -mno-avx, or, to add the flags -Wa,-q

**Comment by maciejkula** [comment]
Yes, this manifests the same as https://github.com/lyst/lightfm/issues/25 (though the root cause is different). I'll have a think.

**Comment by maciejkula** [comment]
I updated #30 to remove the `-march=native` flag. Can you confirm that it works for you?

**Comment by dustinstansbury** [comment]
Removing `-march=native` seems to have addressed the assembly errors. Will let you know if I run into anything else. Thank you for your time!

**Comment by dustinstansbury** [comment]
Hmm, looks like removing the native architecture flag also breaks import of LigthFM, however:

```
ImportError: dlopen(/Users/dustinstansbury/.virtualenvs/test/lib/python2.7/site-packages/lightfm/lightfm_fast.so, 2): no suitable image found.  
Did find:
	/Users/dustinstansbury/.virtualenvs/test/lib/python2.7/site-packages/lightfm/lightfm_fast.so: mach-o, but wrong architecture
```

**Comment by maciejkula** [comment]
I tried many things, but I think the soundest course of action here is to not support the default OSX Python installation. I'll update the readme to that effect.
